### ISSUE TITLE
I used wrk to replace curl app,which can not invoke line, _, err := r.ReadLine()

### ISSUE THREAD

**Issue by 578141611** [hmgle/graftcp#22]
## fail  
./graftcp -p 2233 wrk -t2 -c10 -d10s http://ww.baidu.com
 _, err := r.ReadLine() can not invoke

## ok
wrk -t2 -c10 -d10s http://ww.baidu.com

## ok
./graftcp -p 2233 curl http://ww.baidu.com
 _, err := r.ReadLine() can invoke

**Comment by 578141611** [comment]
wrk in github:
https://github.com/wg/wrk

**Comment by hmgle** [comment]
It is not reproduced on my machine. In order to check if your proxy is stable, you can use `proxychains-ng` to redirect the connection of `wrk`, as `wrk` is dynamically linked, and see if this problem will occur.

BTW, tracking system calls may cause performance loss. Using `graftcp` for benchmarking high concurrency will greatly reduce the result.
