### ISSUE TITLE
graftcp breaks yay

### ISSUE THREAD

**Issue by tewilove** [hmgle/graftcp#64]
Configured graft-local to use a local socks5 server only.
```
[ming@A770 aur]$ graftcp bash
[ming@A770 aur]$ yay -S graftcp
 -> 1 error occurred:
	* request failed: Get "https://aur.archlinux.org/rpc?arg%5B%5D=graftcp&type=info&v=5": EOF


 -> Failed to find AUR package for graftcp:1 error occurred:
	* request failed: Get "https://aur.archlinux.org/rpc?arg=graftcp&by=provides&type=search&v=5": EOF


 -> No AUR package found for graftcp
 there is nothing to do
```

**Comment by hmgle** [comment]
It can't be reproduced on my machine. Can you post the graftcp-local log?

**Comment by hmgle** [comment]
Since I can't reproduce this issue on my host and there are no log to help pinpoint the problem, I'm going to close this issue for now. Additionally, because `yay` actually invokes `sudo pacman ...`, you'll need to use the `-u` parameter to start the command: `sudo graftcp sudo -u $USER yay ...`, or `sudo graftcp -u $USER yay ...`.
