### ISSUE TITLE
the fourth argument register should be %rcx

### ISSUE THREAD

**Issue by HUANGChaoLi** [hmgle/graftcp#9]
``` c
long get_syscall_arg(pid_t pid, int order)
{
	int offset;
	long val;

	switch (order) {
	case 0:
		offset = offsetof(struct user, regs.rdi);
		break;
	case 1:
		offset = offsetof(struct user, regs.rsi);
		break;
	case 2:
		offset = offsetof(struct user, regs.rdx);
		break;
	case 3:
		offset = offsetof(struct user, regs.r10);
		break;
	case 4:
		offset = offsetof(struct user, regs.r8);
		break;
	case 5:
		offset = offsetof(struct user, regs.r9);
		break;
	default:
		return -1;
	}
	errno = 0;
	val = ptrace(PTRACE_PEEKUSER, pid, offset);
	assert(errno == 0);
	return val;
}
```
``` c
case 3:
	offset = offsetof(struct user, regs.r10);
```
![image](https://user-images.githubusercontent.com/13926164/48952955-18289d00-ef7f-11e8-864c-8ce3f7a23722.png)

**Comment by hmgle** [comment]
The syscall use `r10` instead of `rcx` for the fourth argument, so it is not a bug, but it is worth investigating.
This [answer(Why is RCX not used for passing parameters to system calls)](https://stackoverflow.com/questions/32253144/why-is-rcx-not-used-for-passing-parameters-to-system-calls-being-replaced-with/32480482#32480482) explains the reasons for the replacement.
Thank you for the feedback.
